version: "3.9"
services:
  web:
    build: .
    expose:  
      - 8000
    command: >
      bash -c "python manage.py migrate --noinput &&
              gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 1 --threads 4"
    volumes:
      - .:/code

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - .:/code
    depends_on:
      - web
