# Generated by Django 4.2.7 on 2023-11-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("XSTORE", "0002_product_is_popular"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="products"),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="users"),
        ),
    ]
