# Generated by Django 4.2.7 on 2023-11-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("XSTORE", "0003_alter_product_photo_alter_user_photo"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
